[tool.poetry]
name = "lab6"
version = "0.1.0"
description = ""
authors = ["Luhter1 <kaparulinti@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.6"
matplotlib = "^3.10.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
